---
title: "cjs model for survival-rate estimation in 2019-2021-cohort"
author: "Shohei Noda"
date: "2025-02-16"
output: 
  html_document:
    toc: yes
    toc_depth: 5
    toc_float: TRUE
    number_section: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}

# load package
pacman::p_load(tidyverse, runjags, loo)
library(RColorBrewer)

# plot setting
theme_set(
  theme_bw() +
    theme(title = element_text(size=20, family="sans", face="bold"),
          axis.title = element_text(size=20, family="sans", face="bold"),
          axis.text = element_text(size=15, family="sans"),
          strip.text=element_text(size=20, family="sans", face="bold"),
          strip.background = element_rect(color="black", fill="white",
                                          linewidth=0.6, linetype="solid"),
          panel.background = element_rect("white"),
          legend.title = element_text(size = 15, family="sans", face="bold"),
          legend.text = element_text(size = 15, family="sans"),
          legend.position = 'none')
  )

```

# prepare input data

data: 2019-2021 cohorts  

```{r}

# road a model
m <- read.jagsfile("code/model_cjs_r_ver3.R")

# read raw data
d0 <- read.csv("./input_data/rawdata_filtered.csv") 
```

# phi for age-2 to age-3
## edit input data
```{r}
# edit data
dat1 <- d0 %>% 
  mutate(distance = case_when(between(year, 2016, 2019) ~ (new_landmark - 400) * 10,
                              between(year, 2020, 2024) ~ new_landmark * 10),
         age_at_mature2 = case_when(age_at_mature == "0" ~ "0",
                                    age_at_mature == "1" ~ "1",
                                    age_at_mature == "2" ~ "2",
                                    age_at_mature == "3" ~ "2",
                                    age_at_mature == ">1" ~ "2",
                                    age_at_mature == ">2" ~ "2",
                                    age_at_mature == ">3" ~ "2",
                                    TRUE ~ "nd")) %>% 
  filter(distance > 0,
         treatment == "early" | treatment == "late" | treatment == "control",
         between(cohort, 2019, 2021),
         age2_mature != "nd") %>%
  mutate(SecUL = ceiling(distance * 0.1) * 10, # upstream landmark
         SecDL = SecUL - 10, # downstream landmark
         Occasion = as.numeric(factor(year)), # add occasion column
         ) %>%
  filter(id %in% names(which(table(unlist(tapply(id, treatment, unique))) == 1))) %>%  # remove individuals captured in other treatment
  distinct(id,year,month, .keep_all = TRUE)

# check cohort error ids
eid <- dat1 %>% 
  filter(year < cohort) %>% 
  pull(id)

# check y-m
occasion_list <- tibble(
  year = sort(unique(dat1$year)),
  oc = sort(unique((dat1$Occasion)))
)
occasion_list
```

## run CJS model
```{r}
## create history matrices
## - Variable transformation
## - `Occasion` - `year`
## - `CO` - `cohort`
## - `MT` - `age at maturity` 
## Note: An error will occur if there is data with duplicate ID and captured date.

## CH: Capture history - binary information of recaptured or not
CH <- dat1 %>%
  mutate(capture = 1) %>%
  arrange(Occasion) %>%
  pivot_wider(names_from = Occasion,
              values_from = capture,
              id_cols = c(id, cohort, age2_mature),
              values_fill = list(capture = 0)) %>%
  rename(CO = cohort,
         MT = age2_mature) %>%
  mutate(CO = as.numeric(factor(CO)),
         MT = as.factor(MT)) %>%
  arrange(id) # arrange by id

# check number of samples
count <- count(CH, CO, MT)
count

# select sorted occasion data
ch <- CH %>%
  dplyr::select(as.factor(sort(unique(as.numeric(dat1$Occasion)))))

# put NA until the first capture
for(i in 1:nrow(ch)) {
  x <- min(which(ch[i,] == 1)) - 1
  if(x != 0) ch[i, 1:x] <- NA
}

CH[, which(colnames(CH) %in% sort(unique(dat1$Occasion)))] <- ch

print(CH)

## DH: Location history - distance from the downstream end to the upstream landmark of a (re)capture subsection
DH <- dat1 %>%
  arrange(Occasion) %>%
  pivot_wider(names_from = Occasion,
              values_from = SecUL,
              id_cols = c(id, cohort, age2_mature)) %>%
  rename(CO = cohort,
         MT = age2_mature) %>%
  mutate(CO = as.numeric(factor(CO)),
         MT = as.factor(MT)) %>%
  arrange(id)

print(DH)

## JH: Julian history - Julian date of capture for each occasion
JH <- dat1 %>%
  arrange(Occasion) %>%
  pivot_wider(names_from = Occasion,
              values_from = Julian,
              id_cols = c(id, cohort, age2_mature)) %>%
  rename(CO = cohort,
         MT = age2_mature) %>%
  mutate(CO = as.numeric(factor(CO)),
         MT = as.factor(MT)) %>%
  arrange(id)

print(JH)

J <- as.matrix(JH[,which(colnames(JH) == "1"):ncol(JH)]) # make matrix of JH

# mcmc setting
n.ad <- 100
n.iter <- 2E+4
n.thin <- max(3, ceiling(n.iter/500))
burn <- ceiling(max(10, n.iter/2))
Sample <- ceiling(n.iter/n.thin)

# parameter list
para <- c("xi", "mu.p", "sigma.p", "p", "pi", "phi", "alpha")

# bayesian inference
## Data for JAGS
### Response
X <- as.matrix(DH[,which(colnames(DH) == "1"):ncol(DH)] - 5)
Y <- z <- as.matrix(CH[,which(colnames(CH) == "1"):ncol(CH)])
z[Y == 0] <- NA # Y data replaced 0 to NA
ObsF <- apply(Y, 1, function(x) min(which(is.na(x) == 0))) # first observed occasion 
ObsL <- apply(Y, 1, function(x) max(which(x == 1))) # last observed occasion 

# put 1 first to last observed occasion 
for(i in 1:length(ObsF)){
  z[i,ObsF[i]:ObsL[i]] <- 1
}

### Explanatory
Nday <- diff(apply(J, 2, median, na.rm = T)) # interval between occasions
Grid <- count %>% dplyr::select(CO,MT) # Create unique combinations
Grid$G <- 1:length(Grid$CO) # make new no. column
Grid$id <- as.numeric(paste0(Grid$CO,Grid$MT)) # make new id column

# marge Grid and Capture history data (Grouping)
groupdat <- tibble(id = as.numeric(paste0(CH$CO, CH$MT))) %>%
  left_join(Grid, by = "id")

G <- groupdat$G
first_occasion <- Grid %>% 
  mutate(Fo = case_when(CO == 1 ~ 2,
                        CO == 2 ~ 3,
                        CO == 3 ~ 4,
                        CO == 4 ~ 5))

# make input data
Djags <- list(X = X,
              Y = Y,
              Nday = Nday,
              z = z,
              Nind = nrow(Y), # Number of sample
              Nt = ncol(Y), # Number of occasion
              Ng = length(unique(G)), # Number of unique combinations for groups
              G = G, # grouping data
              Fo = first_occasion$Fo,
              ObsF = ObsF
)

# Repeat an equation 3 times
inits <- replicate(3,
                   list(logit.p = matrix(0, nrow = Djags$Ng, ncol = Djags$Nt-1),
                        .RNG.name = "base::Mersenne-Twister",
                        .RNG.seed = NA ),
                   simplify = F)

for(k in 1:3) inits[[k]]$.RNG.seed <- k

# mcmc using runjags
# Parameter estimation by MCMC using runjags
post <- run.jags(m$model,
                 monitor = para,
                 data = Djags,
                 n.chains = 3,
                 inits = inits,
                 method = "parallel",
                 burnin = burn,
                 sample = Sample,
                 adapt = n.ad,
                 thin = n.thin,
                 n.sims = 3,
                 modules = "glm")

# out result
bpost <- MCMCvis::MCMCsummary(post$mcmc,probs = c(0.05,0.5,0.95))

# evaluation of posterior distribution
print(max(na.omit(bpost[, "Rhat"])))

# output
bpost <- bpost %>% 
  as_tibble(rownames = "param") %>% 
  rename(lower = '5%',
         median = '50%',
         upper = '95%')

## convert date
date <- apply(J, 2, median, na.rm = T) %>% 
  as.Date(origin = as.Date("1970-01-01"))

dat_date <- tibble(occasion = 1:length(date),
                   date = date)
dat_date

# make new data
result <- bpost %>% 
  filter(str_detect(param, "phi")) %>% 
  mutate(x = str_extract(param, pattern = "\\[.{1,}\\]"),
         y = str_remove_all(x, pattern = "\\[|\\]")) %>%
  separate(y, into = c("group", "occasion"), sep = ",") %>% 
  mutate(group = as.numeric(group),
         occasion = as.numeric(occasion)) %>% 
  left_join(Grid, by = c("group" = "G")) %>% 
  left_join(dat_date, by = "occasion") %>% 
  mutate(cohort = case_when(CO == 1 ~ "2019",
                            CO == 2 ~ "2020",
                            CO == 3 ~ "2021"),
         age2_maturity = MT,
         year = year(date),
         month = month(date),
         age = year - as.numeric(cohort)) %>% 
  left_join(count, by = c("CO","MT"))  %>% 
  mutate(n = case_when(cohort == "2019" & age2_maturity == 0 ~ paste0('n = ', as.character(n)), TRUE ~ as.character(n)))

# save to csv
write.csv(result, "output/phi_age2_3_age2mature.csv")
```

## plot
```{r}
# filtering
dat_sub <- result %>% 
  filter(age == 3)

g <- ggplot(dat_sub, aes(x = age2_maturity, y = mean, ymin = lower, ymax = upper)) +
  geom_errorbar(width = 0, linewidth = 1, position = position_dodge(.7)) +
  geom_point(size = 4, position = position_dodge(.7)) +
  facet_grid(~cohort) +
  ylab("Survival probability") +
  xlab("Age-2 maturity") +
  scale_y_continuous(limits = c(0, 1.2), breaks=seq(0,1.5,0.5)) +
  geom_text(aes(x = age2_maturity, y = 1.1, label = n), size = 4, 
            position = position_dodge(.7))
g
```


